const abc = {
  request: {
    location: {
      canonicalHref: "https://pixabay.com/music/",
      host: "https://pixabay.com",
      protocol: "https",
      pathname: "/music/",
      path: "/music/",
      href: "https://pixabay.com/music/",
    },
    bootstrapUrl: "",
    userAgent: { isMobile: false, isTablet: false, isBot: false },
    language: "en",
    languages: [
      { code: "cs", name: "Čeština", href: "https://pixabay.com/cs/music/" },
      { code: "da", name: "Dansk", href: "https://pixabay.com/da/music/" },
      { code: "de", name: "Deutsch", href: "https://pixabay.com/de/music/" },
      { code: "en", name: "English", href: "https://pixabay.com/music/" },
      { code: "es", name: "Español", href: "https://pixabay.com/es/music/" },
      { code: "fr", name: "Français", href: "https://pixabay.com/fr/music/" },
      { code: "id", name: "Indonesia", href: "https://pixabay.com/id/music/" },
      { code: "it", name: "Italiano", href: "https://pixabay.com/it/music/" },
      { code: "hu", name: "Magyar", href: "https://pixabay.com/hu/music/" },
      { code: "nl", name: "Nederlands", href: "https://pixabay.com/nl/music/" },
      { code: "no", name: "Norsk", href: "https://pixabay.com/no/music/" },
      { code: "pl", name: "Polski", href: "https://pixabay.com/pl/music/" },
      { code: "pt", name: "Português", href: "https://pixabay.com/pt/music/" },
      { code: "ro", name: "Română", href: "https://pixabay.com/ro/music/" },
      { code: "sk", name: "Slovenčina", href: "https://pixabay.com/sk/music/" },
      { code: "fi", name: "Suomi", href: "https://pixabay.com/fi/music/" },
      { code: "sv", name: "Svenska", href: "https://pixabay.com/sv/music/" },
      { code: "tr", name: "Türkçe", href: "https://pixabay.com/tr/music/" },
      { code: "vi", name: "Việt", href: "https://pixabay.com/vi/music/" },
      { code: "th", name: "ไทย", href: "https://pixabay.com/th/music/" },
      { code: "bg", name: "Български", href: "https://pixabay.com/bg/music/" },
      { code: "ru", name: "Русский", href: "https://pixabay.com/ru/music/" },
      { code: "el", name: "Ελληνική", href: "https://pixabay.com/el/music/" },
      { code: "ja", name: "日本語", href: "https://pixabay.com/ja/music/" },
      { code: "ko", name: "한국어", href: "https://pixabay.com/ko/music/" },
      { code: "zh", name: "简体中文", href: "https://pixabay.com/zh/music/" },
    ],
    languageUrlPrefix: "",
    noindex: false,
    nofollow: false,
    seo: {
      metaTitle: "Royalty Free Music Download",
      metaDescription:
        "Open source resource, download royalty free audio music MP3 tracks ✓ Free for commercial use ✓ No attribution required",
      h1Text: "Royalty free music downloads",
      h2Text:
        "Over 120,000+ free music tracks shared by our talented community.",
      relatedKeywords: [],
    },
    ogTags: { title: "", description: "", image: "" },
    i18nStrings: {},
    gtmNoscriptSnippetParams:
      "id=GTM-5CF9ZN&gtm_auth=EzJCsJwDfVlqG8d1K6KKOg&gtm_preview=env-1&gtm_cookies_win=x",
    gtmScriptSnippet:
      "<scr" +
      "ipt>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl+ '&gtm_auth=EzJCsJwDfVlqG8d1K6KKOg&gtm_preview=env-1&gtm_cookies_win=x';f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-5CF9ZN');</scr" +
      "ipt>",
    dataLayer: [{}],
    user: {
      id: 16511959,
      username: "ShivanshShalabh",
      firstName: "Shivansh",
      lastName: "Shalabh",
      email: "shalabhshivansh@gmail.com",
      isActive: true,
      isAnonymous: false,
      isStaff: false,
      isSuperuser: false,
      isReliable: false,
      permissions: [],
      lastLogin: "2023-03-17 12:46:36.549300",
      uploadsDisabled: false,
      editTagsDisabled: false,
      messageCount: 0,
      profileImage: "/static/img/profile_image_dummy.svg",
      profileImage2x: "/static/img/profile_image_dummy.svg",
      profileUrl: "/users/shivanshshalabh-16511959/",
      unreadNotificationsCount: 0,
      showRecaptcha: true,
      canReportSpamComments: false,
      permittedUploads: 7,
    },
    adminTools: [],
    flags: {},
    serviceCredentials: {
      googleClientId: "575185734362.apps.googleusercontent.com",
      facebookAppId: "114593902037957",
      recaptchaSiteKey: "6LeyhLIaAAAAAI8XfF3RoG62z0L0RLUrgGVb1p_z",
      wechatAppId: "wx51b436351abaf7b7",
      oneTrustSdkUrl:
        "https://cdn-au.onetrust.com/scripttemplates/otSDKStub.js",
      oneTrustSdkDomainScript: "52f0ce5e-0c2d-48a6-8e40-e978c5058a96",
    },
    security: {
      timestamp: "1679123138",
      hash: "7536e76ef3477ca5062911bbc717b721bde2fcbf",
      signature: "ssr:1pdQdG:HdOKIjffgETlUbi_t0gVa2uk5wkrOQmw_e62uFVY_ts",
    },
    auth: {
      loginUrlTemplate: "/accounts/login/",
      registerUrlTemplate: "/accounts/register/",
      socialAuthUrlTemplate: "/accounts/auth/{provider}/",
      wechatAuthIframeUrlTemplate: "/accounts/auth/wechat/iframe/",
      resendConfirmEmailUrlTemplate:
        "/accounts/register/resend_confirmation/?pk={userId}",
      resetPasswordUrlTemplate: "/accounts/reset_password/",
    },
    featureFlags: {
      useWechatAuth: false,
      useCloudflareSuggestions: true,
      useAnimations: true,
      showNewGettyCopy: false,
      gettyTrackClicks: true,
      useTransparentStatus: false,
      reactAttributionAds: false,
    },
    collectVitalsUrl: "/collect/web-vitals/",
    collectVitalsSampleRate: 1,
    sentrySampleRate: 0,
    mediaCount: 3,
    likedMedia: [],
    collectedMedia: [],
    followedUsers: [],
  },
  page: {
    pageType: "media_index",
    mediaType: "audio",
    searchType: "music",
    urlTemplate: "/",
    searchUrlTemplate: "/{searchType}/search/{query}/",
    results: [
      {
        id: 142819,
        mediaType: "audio",
        mediaSubType: 3,
        duration: 97,
        uploadDate: "2023-03-18T06:14:09.352721",
        href: "https://pixabay.com/music/beats-floating-abstract-142819/",
        sources: {
          src: "https://cdn.pixabay.com/audio/2023/03/16/audio_df7d9198c3.mp3",
          waveformUrl: "/music/142819/waveform.json",
          thumbnailUrl: "",
          thumbnailOrientation: "portrait",
          downloadUrl:
            "https://cdn.pixabay.com/download/audio/2023/03/16/audio_df7d9198c3.mp3?filename=floating-abstract-142819.mp3",
        },
        alt: "Abstract, Beat, Clean, Electronica",
        title: null,
        description: "Abstract, Beat, Clean, Electronica, Floating, Futuristic",
        name: "Floating Abstract",
        nsfw: false,
        tagLinks:
          '<a href="/music/search/abstract/">abstract</a> <a href="/music/search/beat/">beat</a> <a href="/music/search/clean/">clean</a>',
        likeCount: 41,
        likeHref: "/accounts/like/audio/142819/",
        commentCount: 0,
        commentHref: "/music/beats-floating-abstract-142819/#comments",
        contentIdCertificateUrl: "/music/142819/license/",
        attributionHtml:
          'Music by <a href="https://pixabay.com/users/comastudio-26079283/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=142819">ComaStudio</a> from <a href="https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=142819">Pixabay</a>',
        vector: false,
        isEditorsChoice: true,
        isLowQuality: false,
        qualityStatus: 5,
        rating: 9,
        user: {
          id: 26079283,
          username: "ComaStudio",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2022/03/10/11-06-25-684_96x96.jpg",
          profileUrl: "/users/comastudio-26079283/",
          socialLinks: [],
          donation: {
            paypal: "https://www.patreon.com/yuriisemchyshyn",
            method: 1,
          },
          followerCount: 0,
          aboutMe: "",
        },
      },
      {
        id: 142569,
        mediaType: "audio",
        mediaSubType: 3,
        duration: 128,
        uploadDate: "2023-03-18T06:14:09.353598",
        href: "https://pixabay.com/music/acoustic-group-coniferous-forest-142569/",
        sources: {
          src: "https://cdn.pixabay.com/audio/2023/03/14/audio_676747013a.mp3",
          waveformUrl: "/music/142569/waveform.json",
          thumbnailUrl: "",
          thumbnailOrientation: "portrait",
          downloadUrl:
            "https://cdn.pixabay.com/download/audio/2023/03/14/audio_676747013a.mp3?filename=coniferous-forest-142569.mp3",
        },
        alt: "Acoustic, Guitar",
        title: null,
        description: "Acoustic, Guitar",
        name: "Coniferous forest",
        nsfw: false,
        tagLinks:
          '<a href="/music/search/acoustic/">acoustic</a> <a href="/music/search/guitar/">guitar</a>',
        likeCount: 77,
        likeHref: "/accounts/like/audio/142569/",
        commentCount: 0,
        commentHref: "/music/acoustic-group-coniferous-forest-142569/#comments",
        contentIdCertificateUrl: "/music/142569/license/",
        attributionHtml:
          'Music by <a href="https://pixabay.com/users/orangery-34071953/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=142569">orangery</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=142569">Pixabay</a>',
        vector: false,
        isEditorsChoice: true,
        isLowQuality: false,
        qualityStatus: 5,
        rating: 9,
        user: {
          id: 34071953,
          username: "orangery",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2023/03/02/13-35-19-515_96x96.jpg",
          profileUrl: "/users/orangery-34071953/",
          socialLinks: [],
          donation: { paypal: "GQLW8HTBN6RQ6", method: 2 },
          followerCount: 0,
          aboutMe: "",
        },
      },
      {
        id: 140894,
        mediaType: "audio",
        mediaSubType: 3,
        duration: 164,
        uploadDate: "2023-03-18T06:14:09.354235",
        href: "https://pixabay.com/music/adventure-waterfall-140894/",
        sources: {
          src: "https://cdn.pixabay.com/audio/2023/02/28/audio_550d815fa5.mp3",
          waveformUrl: "/music/140894/waveform.json",
          thumbnailUrl:
            "https://cdn.pixabay.com/audio/2023/02/28/09-32-41-52_200x200.png",
          thumbnailOrientation: "portrait",
          downloadUrl:
            "https://cdn.pixabay.com/download/audio/2023/02/28/audio_550d815fa5.mp3?filename=waterfall-140894.mp3",
        },
        alt: "Great, emotional, impressive and inspiring music track. The song begins with calm rhythm and soft guitar’s atmospheric notes, then piano joins in with simple melody, after that you can hear full and rich sound of low synth with drums and acoustic guitars.",
        title: null,
        description: "Atmosphere, Atmospheric, Background, Calm, Cinematic",
        name: "Waterfall",
        nsfw: false,
        tagLinks:
          '<a href="/music/search/atmosphere/">atmosphere</a> <a href="/music/search/atmospheric/">atmospheric</a>',
        likeCount: 486,
        likeHref: "/accounts/like/audio/140894/",
        commentCount: 13,
        commentHref: "/music/adventure-waterfall-140894/#comments",
        contentIdCertificateUrl: "/music/140894/license/",
        attributionHtml:
          'Music by <a href="https://pixabay.com/users/romansenykmusic-11989248/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=140894">RomanSenykMusic</a> from <a href="https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=140894">Pixabay</a>',
        vector: false,
        isEditorsChoice: true,
        isLowQuality: false,
        qualityStatus: 5,
        rating: 9,
        user: {
          id: 11989248,
          username: "RomanSenykMusic",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2023/01/11/22-32-15-627_96x96.png",
          profileUrl: "/users/romansenykmusic-11989248/",
          socialLinks: [],
          donation: { paypal: "lidiiasenyk@gmail.com", method: 2 },
          followerCount: 0,
          aboutMe: "",
        },
      },
      {
        id: 140795,
        mediaType: "audio",
        mediaSubType: 3,
        duration: 139,
        uploadDate: "2023-03-18T06:14:09.354844",
        href: "https://pixabay.com/music/future-bass-modern-vlog-140795/",
        sources: {
          src: "https://cdn.pixabay.com/audio/2023/02/27/audio_5d7788ef2d.mp3",
          waveformUrl: "/music/140795/waveform.json",
          thumbnailUrl:
            "https://cdn.pixabay.com/audio/2023/02/27/20-30-59-858_200x200.png",
          thumbnailOrientation: "portrait",
          downloadUrl:
            "https://cdn.pixabay.com/download/audio/2023/02/27/audio_5d7788ef2d.mp3?filename=modern-vlog-140795.mp3",
        },
        alt: "",
        title: null,
        description: "",
        name: "Modern Vlog",
        nsfw: false,
        tagLinks:
          '<a href="/music/search/genre/Future Bass/">Future Bass</a> <a href="/music/search/mood/Uplifting/">Uplifting</a> <a href="/music/search/movement/Floating/">Floating</a>',
        likeCount: 288,
        likeHref: "/accounts/like/audio/140795/",
        commentCount: 0,
        commentHref: "/music/future-bass-modern-vlog-140795/#comments",
        contentIdCertificateUrl: "/music/140795/license/",
        attributionHtml:
          'Music by <a href="https://pixabay.com/users/penguinmusic-24940186/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=140795">penguinmusic</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=140795">Pixabay</a>',
        vector: false,
        isEditorsChoice: true,
        isLowQuality: false,
        qualityStatus: 5,
        rating: 9,
        user: {
          id: 24940186,
          username: "penguinmusic",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2021/12/27/04-06-14-169_96x96.png",
          profileUrl: "/users/penguinmusic-24940186/",
          socialLinks: [],
          donation: { paypal: "creo.musick@gmail.com", method: 2 },
          followerCount: 0,
          aboutMe: "",
        },
      },
      {
        id: 137766,
        mediaType: "audio",
        mediaSubType: 3,
        duration: 165,
        uploadDate: "2023-03-18T06:14:09.355410",
        href: "https://pixabay.com/music/acoustic-group-easy-lifestyle-137766/",
        sources: {
          src: "https://cdn.pixabay.com/audio/2023/02/03/audio_534a89f910.mp3",
          waveformUrl: "/music/137766/waveform.json",
          thumbnailUrl: "",
          thumbnailOrientation: "portrait",
          downloadUrl:
            "https://cdn.pixabay.com/download/audio/2023/02/03/audio_534a89f910.mp3?filename=easy-lifestyle-137766.mp3",
        },
        alt: "Lifestyle, Easy, Chill, Electronic",
        title: null,
        description: "Lifestyle, Easy, Chill, Electronic, Inspire, Nspiration",
        name: "Easy Lifestyle",
        nsfw: false,
        tagLinks:
          '<a href="/music/search/lifestyle/">lifestyle</a> <a href="/music/search/easy/">easy</a> <a href="/music/search/chill/">chill</a>',
        likeCount: 826,
        likeHref: "/accounts/like/audio/137766/",
        commentCount: 0,
        commentHref: "/music/acoustic-group-easy-lifestyle-137766/#comments",
        contentIdCertificateUrl: "/music/137766/license/",
        attributionHtml:
          'Music by <a href="https://pixabay.com/users/lesfm-22579021/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=137766">Lesfm</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=137766">Pixabay</a>',
        vector: false,
        isEditorsChoice: true,
        isLowQuality: false,
        qualityStatus: 5,
        rating: 9,
        user: {
          id: 22579021,
          username: "Lesfm",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2022/06/18/09-26-46-83_96x96.png",
          profileUrl: "/users/lesfm-22579021/",
          socialLinks: [],
          donation: { paypal: "GQLW8HTBN6RQ6", method: 2 },
          followerCount: 0,
          aboutMe: "",
        },
      },
      {
        id: 136788,
        mediaType: "audio",
        mediaSubType: 3,
        duration: 72,
        uploadDate: "2023-03-18T06:14:09.356017",
        href: "https://pixabay.com/music/main-title-risk-136788/",
        sources: {
          src: "https://cdn.pixabay.com/audio/2023/01/27/audio_3d61eda8c6.mp3",
          waveformUrl: "/music/136788/waveform.json",
          thumbnailUrl:
            "https://cdn.pixabay.com/audio/2023/01/27/10-02-46-157_200x200.jpg",
          thumbnailOrientation: "portrait",
          downloadUrl:
            "https://cdn.pixabay.com/download/audio/2023/01/27/audio_3d61eda8c6.mp3?filename=risk-136788.mp3",
        },
        alt: "Cinematic, Trailer, Blockbuster, Movie",
        title: null,
        description: "Cinematic, Trailer, Blockbuster, Movie, Dramatic, Action",
        name: "Risk",
        nsfw: false,
        tagLinks:
          '<a href="/music/search/cinematic/">cinematic</a> <a href="/music/search/trailer/">trailer</a>',
        likeCount: 932,
        likeHref: "/accounts/like/audio/136788/",
        commentCount: 20,
        commentHref: "/music/main-title-risk-136788/#comments",
        contentIdCertificateUrl: "/music/136788/license/",
        attributionHtml:
          'Music by <a href="https://pixabay.com/users/studiokolomna-2073170/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=136788">StudioKolomna</a> from <a href="https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=136788">Pixabay</a>',
        vector: false,
        isEditorsChoice: true,
        isLowQuality: false,
        qualityStatus: 5,
        rating: 9,
        user: {
          id: 2073170,
          username: "StudioKolomna",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2022/07/04/12-42-22-460_96x96.png",
          profileUrl: "/users/studiokolomna-2073170/",
          socialLinks: [],
          donation: null,
          followerCount: 0,
          aboutMe: "",
        },
      },
      {
        id: 136824,
        mediaType: "audio",
        mediaSubType: 3,
        duration: 180,
        uploadDate: "2023-03-18T06:14:09.356601",
        href: "https://pixabay.com/music/main-title-awaken-136824/",
        sources: {
          src: "https://cdn.pixabay.com/audio/2023/01/27/audio_e649bbdf58.mp3",
          waveformUrl: "/music/136824/waveform.json",
          thumbnailUrl:
            "https://cdn.pixabay.com/audio/2023/01/31/09-58-23-591_200x200.jpg",
          thumbnailOrientation: "portrait",
          downloadUrl:
            "https://cdn.pixabay.com/download/audio/2023/01/27/audio_e649bbdf58.mp3?filename=awaken-136824.mp3",
        },
        alt: "Awaken - is a beautiful and sad cinematic background music for videos, films, documentaries, cinematic scenes, for drama, emotional moments, memories, photo slodeshow, podcasts, TV and radio shows, websites, social media, Facebook, Instagram, YouTube videos, Vimeo videos, TikTok",
        title: null,
        description: "Calm, Cinematic, Commercial, Despair, Documentary, Drama",
        name: "Awaken",
        nsfw: false,
        tagLinks:
          '<a href="/music/search/calm/">calm</a> <a href="/music/search/cinematic/">cinematic</a>',
        likeCount: 639,
        likeHref: "/accounts/like/audio/136824/",
        commentCount: 20,
        commentHref: "/music/main-title-awaken-136824/#comments",
        contentIdCertificateUrl: "/music/136824/license/",
        attributionHtml:
          'Music by <a href="https://pixabay.com/users/oystudio-24430395/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=136824">OYStudio</a> from <a href="https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=136824">Pixabay</a>',
        vector: false,
        isEditorsChoice: true,
        isLowQuality: false,
        qualityStatus: 5,
        rating: 9,
        user: {
          id: 24430395,
          username: "OYStudio",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2023/01/17/08-52-02-587_96x96.png",
          profileUrl: "/users/oystudio-24430395/",
          socialLinks: [],
          donation: { paypal: "onoychenko.e@gmail.com", method: 2 },
          followerCount: 0,
          aboutMe: "",
        },
      },
      {
        id: 132333,
        mediaType: "audio",
        mediaSubType: 3,
        duration: 76,
        uploadDate: "2023-03-18T06:14:09.357165",
        href: "https://pixabay.com/music/acoustic-group-a-small-miracle-132333/",
        sources: {
          src: "https://cdn.pixabay.com/audio/2023/01/06/audio_d74b2d0ff4.mp3",
          waveformUrl: "/music/132333/waveform.json",
          thumbnailUrl:
            "https://cdn.pixabay.com/audio/2023/01/06/10-39-24-970_200x200.jpg",
          thumbnailOrientation: "portrait",
          downloadUrl:
            "https://cdn.pixabay.com/download/audio/2023/01/06/audio_d74b2d0ff4.mp3?filename=a-small-miracle-132333.mp3",
        },
        alt: "Acoustic, Ukulele, Light, Mellow, Serene",
        title: null,
        description: "Acoustic, Ukulele, Light, Mellow, Serene, Subtle, Summer",
        name: "A Small Miracle",
        nsfw: false,
        tagLinks:
          '<a href="/music/search/acoustic/">acoustic</a> <a href="/music/search/ukulele/">ukulele</a> <a href="/music/search/light/">light</a>',
        likeCount: 742,
        likeHref: "/accounts/like/audio/132333/",
        commentCount: 0,
        commentHref: "/music/acoustic-group-a-small-miracle-132333/#comments",
        contentIdCertificateUrl: "/music/132333/license/",
        attributionHtml:
          'Music by <a href="https://pixabay.com/users/romarecord1973-28931782/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=132333">Romarecord1973</a> from <a href="https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=132333">Pixabay</a>',
        vector: false,
        isEditorsChoice: true,
        isLowQuality: false,
        qualityStatus: 5,
        rating: 9,
        user: {
          id: 28931782,
          username: "Romarecord1973",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2022/07/30/11-57-26-419_96x96.jpg",
          profileUrl: "/users/romarecord1973-28931782/",
          socialLinks: [],
          donation: { paypal: "romarecord1973@gmail.com", method: 2 },
          followerCount: 0,
          aboutMe: "",
        },
      },
      {
        id: 131746,
        mediaType: "audio",
        mediaSubType: 3,
        duration: 140,
        uploadDate: "2023-03-18T06:14:09.357798",
        href: "https://pixabay.com/music/beats-relaxed-vlog-night-street-131746/",
        sources: {
          src: "https://cdn.pixabay.com/audio/2023/01/01/audio_816821e627.mp3",
          waveformUrl: "/music/131746/waveform.json",
          thumbnailUrl:
            "https://cdn.pixabay.com/audio/2023/01/01/02-21-06-772_200x200.jpg",
          thumbnailOrientation: "portrait",
          downloadUrl:
            "https://cdn.pixabay.com/download/audio/2023/01/01/audio_816821e627.mp3?filename=relaxed-vlog-night-street-131746.mp3",
        },
        alt: "if you enjoy and use this music in your project you can donate me (any donation by your Heart as your big Thanks for my creativity) to my PayPal: https://www.paypal.com/paypalme/adcomposer Thank you! Composer: DANIELYAN ASHOT MAKICHEVICH (IPI NAME 00855552512), UNITED STATES BMI.",
        title: null,
        description: "Hip Hop, Lo-Fi, Lounge, Time-Lapse, Vinyl, Ambient",
        name: "Relaxed Vlog (Night Street)",
        nsfw: false,
        tagLinks:
          '<a href="/music/search/hip%20hop/">hip hop</a> <a href="/music/search/lo-fi/">lo-fi</a> <a href="/music/search/lounge/">lounge</a>',
        likeCount: 1169,
        likeHref: "/accounts/like/audio/131746/",
        commentCount: 36,
        commentHref: "/music/beats-relaxed-vlog-night-street-131746/#comments",
        contentIdCertificateUrl: "/music/131746/license/",
        attributionHtml:
          'Music by <a href="https://pixabay.com/users/ashot-danielyan-composer-27049680/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=131746">Ashot-Danielyan-Composer</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=131746">Pixabay</a>',
        vector: false,
        isEditorsChoice: true,
        isLowQuality: false,
        qualityStatus: 5,
        rating: 8.5,
        user: {
          id: 27049680,
          username: "Ashot-Danielyan-Composer",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2022/05/01/01-22-12-683_96x96.jpg",
          profileUrl: "/users/ashot-danielyan-composer-27049680/",
          socialLinks: [],
          donation: { paypal: "NH4DERR33TD6S", method: 2 },
          followerCount: 0,
          aboutMe: "",
        },
      },
      {
        id: 131566,
        mediaType: "audio",
        mediaSubType: 3,
        duration: 48,
        uploadDate: "2023-03-18T06:14:09.358368",
        href: "https://pixabay.com/music/suspense-dark-mystery-trailer-taking-our-time-131566/",
        sources: {
          src: "https://cdn.pixabay.com/audio/2022/12/29/audio_265ab80d58.mp3",
          waveformUrl: "/music/131566/waveform.json",
          thumbnailUrl:
            "https://cdn.pixabay.com/audio/2022/12/29/19-57-46-594_200x200.jpg",
          thumbnailOrientation: "portrait",
          downloadUrl:
            "https://cdn.pixabay.com/download/audio/2022/12/29/audio_265ab80d58.mp3?filename=dark-mystery-trailer-taking-our-time-131566.mp3",
        },
        alt: "",
        title: null,
        description: "",
        name: "Dark Mystery Trailer (Taking Our time)",
        nsfw: false,
        tagLinks:
          '<a href="/music/search/genre/Suspense/">Suspense</a> <a href="/music/search/mood/Epic/">Epic</a> <a href="/music/search/movement/Chasing/">Chasing</a>',
        likeCount: 995,
        likeHref: "/accounts/like/audio/131566/",
        commentCount: 22,
        commentHref:
          "/music/suspense-dark-mystery-trailer-taking-our-time-131566/#comments",
        contentIdCertificateUrl: "/music/131566/license/",
        attributionHtml:
          'Music by <a href="https://pixabay.com/users/alexgrohl-25289918/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=131566">AlexGrohl</a> from <a href="https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=131566">Pixabay</a>',
        vector: false,
        isEditorsChoice: true,
        isLowQuality: false,
        qualityStatus: 5,
        rating: 9,
        user: {
          id: 25289918,
          username: "AlexGrohl",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2022/01/17/20-49-59-75_96x96.jpg",
          profileUrl: "/users/alexgrohl-25289918/",
          socialLinks: [],
          donation: { paypal: "domosy@gmail.com", method: 2 },
          followerCount: 0,
          aboutMe: "",
        },
      },
      {
        id: 131283,
        mediaType: "audio",
        mediaSubType: 3,
        duration: 92,
        uploadDate: "2023-03-18T06:14:09.358923",
        href: "https://pixabay.com/music/beats-abstract-fashion-pop-131283/",
        sources: {
          src: "https://cdn.pixabay.com/audio/2022/12/27/audio_d6b5851a2b.mp3",
          waveformUrl: "/music/131283/waveform.json",
          thumbnailUrl: "",
          thumbnailOrientation: "portrait",
          downloadUrl:
            "https://cdn.pixabay.com/download/audio/2022/12/27/audio_d6b5851a2b.mp3?filename=abstract-fashion-pop-131283.mp3",
        },
        alt: "Beat, Calm, Chill, Chilled, Cocking",
        title: null,
        description:
          "Beat, Calm, Chill, Chilled, Cocking, Coffee, Fashion, Food",
        name: "Abstract Fashion Pop",
        nsfw: false,
        tagLinks:
          '<a href="/music/search/beat/">beat</a> <a href="/music/search/calm/">calm</a> <a href="/music/search/chill/">chill</a>',
        likeCount: 871,
        likeHref: "/accounts/like/audio/131283/",
        commentCount: 0,
        commentHref: "/music/beats-abstract-fashion-pop-131283/#comments",
        contentIdCertificateUrl: "/music/131283/license/",
        attributionHtml:
          'Music by <a href="https://pixabay.com/users/qubesounds-24397640/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=131283">QubeSounds</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=131283">Pixabay</a>',
        vector: false,
        isEditorsChoice: true,
        isLowQuality: false,
        qualityStatus: 5,
        rating: 9,
        user: {
          id: 24397640,
          username: "QubeSounds",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2022/03/14/11-01-37-197_96x96.png",
          profileUrl: "/users/qubesounds-24397640/",
          socialLinks: [],
          donation: {
            paypal: "https://www.patreon.com/yuriisemchyshyn",
            method: 1,
          },
          followerCount: 0,
          aboutMe: "",
        },
      },
      {
        id: 126735,
        mediaType: "audio",
        mediaSubType: 3,
        duration: 144,
        uploadDate: "2023-03-18T06:14:09.359478",
        href: "https://pixabay.com/music/future-bass-lifelike-126735/",
        sources: {
          src: "https://cdn.pixabay.com/audio/2022/11/22/audio_febc508520.mp3",
          waveformUrl: "/music/126735/waveform.json",
          thumbnailUrl:
            "https://cdn.pixabay.com/audio/2022/11/22/06-30-38-127_200x200.jpg",
          thumbnailOrientation: "portrait",
          downloadUrl:
            "https://cdn.pixabay.com/download/audio/2022/11/22/audio_febc508520.mp3?filename=lifelike-126735.mp3",
        },
        alt: "This is track on Spotify: https://open.spotify.com/album/1yHGAmcy2cUDhq1xJyoYvs",
        title: null,
        description:
          "Technology, Abstract, Life-Like, Timelapse, Hip Hop, Glitch",
        name: "Lifelike",
        nsfw: false,
        tagLinks:
          '<a href="/music/search/technology/">technology</a> <a href="/music/search/abstract/">abstract</a>',
        likeCount: 2188,
        likeHref: "/accounts/like/audio/126735/",
        commentCount: 104,
        commentHref: "/music/future-bass-lifelike-126735/#comments",
        contentIdCertificateUrl: null,
        attributionHtml:
          'Music by <a href="https://pixabay.com/users/alexiaction-26977400/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=126735">AlexiAction</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=126735">Pixabay</a>',
        vector: false,
        isEditorsChoice: true,
        isLowQuality: false,
        qualityStatus: 5,
        rating: 9,
        user: {
          id: 26977400,
          username: "AlexiAction",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2022/04/24/14-49-29-962_96x96.jpg",
          profileUrl: "/users/alexiaction-26977400/",
          socialLinks: [],
          donation: { paypal: "void.creative.lab@gmail.com", method: 2 },
          followerCount: 0,
          aboutMe: "",
        },
      },
      {
        id: 125573,
        mediaType: "audio",
        mediaSubType: 3,
        duration: 208,
        uploadDate: "2023-03-18T06:14:09.360050",
        href: "https://pixabay.com/music/beautiful-plays-mountain-path-125573/",
        sources: {
          src: "https://cdn.pixabay.com/audio/2022/11/11/audio_684ca37dc0.mp3",
          waveformUrl: "/music/125573/waveform.json",
          thumbnailUrl: "",
          thumbnailOrientation: "portrait",
          downloadUrl:
            "https://cdn.pixabay.com/download/audio/2022/11/11/audio_684ca37dc0.mp3?filename=mountain-path-125573.mp3",
        },
        alt: "Scenery, Mountain, Beautiful",
        title: null,
        description:
          "Scenery, Mountain, Beautiful, Concentration, Nature, Walk",
        name: "Mountain Path",
        nsfw: false,
        tagLinks:
          '<a href="/music/search/scenery/">scenery</a> <a href="/music/search/mountain/">mountain</a>',
        likeCount: 1038,
        likeHref: "/accounts/like/audio/125573/",
        commentCount: 39,
        commentHref: "/music/beautiful-plays-mountain-path-125573/#comments",
        contentIdCertificateUrl: "/music/125573/license/",
        attributionHtml:
          'Music by <a href="https://pixabay.com/users/magnetic_trailer-27466606/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=125573">Magnetic_Trailer</a> from <a href="https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=125573">Pixabay</a>',
        vector: false,
        isEditorsChoice: true,
        isLowQuality: false,
        qualityStatus: 5,
        rating: 9,
        user: {
          id: 27466606,
          username: "Magnetic_Trailer",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2022/05/17/12-17-18-738_96x96.jpg",
          profileUrl: "/users/magnetic_trailer-27466606/",
          socialLinks: [],
          donation: { paypal: "GQLW8HTBN6RQ6", method: 2 },
          followerCount: 0,
          aboutMe: "",
        },
      },
      {
        id: 125566,
        mediaType: "audio",
        mediaSubType: 3,
        duration: 175,
        uploadDate: "2023-03-18T06:14:09.360623",
        href: "https://pixabay.com/music/beautiful-plays-please-calm-my-mind-125566/",
        sources: {
          src: "https://cdn.pixabay.com/audio/2022/11/11/audio_84306ee149.mp3",
          waveformUrl: "/music/125566/waveform.json",
          thumbnailUrl: "",
          thumbnailOrientation: "portrait",
          downloadUrl:
            "https://cdn.pixabay.com/download/audio/2022/11/11/audio_84306ee149.mp3?filename=please-calm-my-mind-125566.mp3",
        },
        alt: "Relax, Relaxing, Calm, Calm Down, Piano",
        title: null,
        description: "Relax, Relaxing, Calm, Calm Down, Piano, Relaxing Music",
        name: "Please Calm My Mind",
        nsfw: false,
        tagLinks:
          '<a href="/music/search/relax/">relax</a> <a href="/music/search/relaxing/">relaxing</a> <a href="/music/search/calm/">calm</a>',
        likeCount: 917,
        likeHref: "/accounts/like/audio/125566/",
        commentCount: 0,
        commentHref:
          "/music/beautiful-plays-please-calm-my-mind-125566/#comments",
        contentIdCertificateUrl: "/music/125566/license/",
        attributionHtml:
          'Music by <a href="https://pixabay.com/users/lesfm-22579021/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=125566">Lesfm</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=125566">Pixabay</a>',
        vector: false,
        isEditorsChoice: true,
        isLowQuality: false,
        qualityStatus: 5,
        rating: 9,
        user: {
          id: 22579021,
          username: "Lesfm",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2022/06/18/09-26-46-83_96x96.png",
          profileUrl: "/users/lesfm-22579021/",
          socialLinks: [],
          donation: { paypal: "GQLW8HTBN6RQ6", method: 2 },
          followerCount: 0,
          aboutMe: "",
        },
      },
      {
        id: 124014,
        mediaType: "audio",
        mediaSubType: 3,
        duration: 102,
        uploadDate: "2023-03-18T06:14:09.361187",
        href: "https://pixabay.com/music/beats-drop-it-124014/",
        sources: {
          src: "https://cdn.pixabay.com/audio/2022/10/25/audio_3ea72d75c6.mp3",
          waveformUrl: "/music/124014/waveform.json",
          thumbnailUrl: "",
          thumbnailOrientation: "portrait",
          downloadUrl:
            "https://cdn.pixabay.com/download/audio/2022/10/25/audio_3ea72d75c6.mp3?filename=drop-it-124014.mp3",
        },
        alt: "Style, Stylish, Fashion, Edgy, Cool",
        title: null,
        description:
          "Style, Stylish, Fashion, Edgy, Cool, Smoulder, Smouldering",
        name: "Drop It",
        nsfw: false,
        tagLinks:
          '<a href="/music/search/style/">style</a> <a href="/music/search/stylish/">stylish</a> <a href="/music/search/fashion/">fashion</a>',
        likeCount: 1917,
        likeHref: "/accounts/like/audio/124014/",
        commentCount: 0,
        commentHref: "/music/beats-drop-it-124014/#comments",
        contentIdCertificateUrl: "/music/124014/license/",
        attributionHtml:
          'Music by <a href="https://pixabay.com/users/coma-media-24399569/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=124014">Coma-Media</a> from <a href="https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=124014">Pixabay</a>',
        vector: false,
        isEditorsChoice: true,
        isLowQuality: false,
        qualityStatus: 5,
        rating: 9,
        user: {
          id: 24399569,
          username: "Coma-Media",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2021/11/22/12-58-14-771_96x96.jpeg",
          profileUrl: "/users/coma-media-24399569/",
          socialLinks: [],
          donation: {
            paypal: "https://www.patreon.com/yuriisemchyshyn",
            method: 1,
          },
          followerCount: 0,
          aboutMe: "",
        },
      },
      {
        id: 123276,
        mediaType: "audio",
        mediaSubType: 3,
        duration: 145,
        uploadDate: "2023-03-18T06:14:09.361792",
        href: "https://pixabay.com/music/beats-password-infinity-123276/",
        sources: {
          src: "https://cdn.pixabay.com/audio/2022/10/18/audio_31c2730e64.mp3",
          waveformUrl: "/music/123276/waveform.json",
          thumbnailUrl:
            "https://cdn.pixabay.com/audio/2022/10/18/12-55-08-891_200x200.jpg",
          thumbnailOrientation: "portrait",
          downloadUrl:
            "https://cdn.pixabay.com/download/audio/2022/10/18/audio_31c2730e64.mp3?filename=password-infinity-123276.mp3",
        },
        alt: "Trap, Atmospheric, Synthwave, Fonk, Neon",
        title: null,
        description:
          "Trap, Atmospheric, Synthwave, Fonk, Neon, Noire, Moody, Dark",
        name: "Password Infinity",
        nsfw: false,
        tagLinks:
          '<a href="/music/search/trap/">trap</a> <a href="/music/search/atmospheric/">atmospheric</a>',
        likeCount: 985,
        likeHref: "/accounts/like/audio/123276/",
        commentCount: 0,
        commentHref: "/music/beats-password-infinity-123276/#comments",
        contentIdCertificateUrl: "/music/123276/license/",
        attributionHtml:
          'Music by <a href="https://pixabay.com/users/evgeny_bardyuzha-25235210/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=123276">Evgeny_Bardyuzha</a> from <a href="https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=123276">Pixabay</a>',
        vector: false,
        isEditorsChoice: true,
        isLowQuality: false,
        qualityStatus: 5,
        rating: 9,
        user: {
          id: 25235210,
          username: "Evgeny_Bardyuzha",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2022/01/18/14-43-38-137_96x96.jpg",
          profileUrl: "/users/evgeny_bardyuzha-25235210/",
          socialLinks: [],
          donation: {
            paypal: "https://www.paypal.me/evgenybardyuzha",
            method: 1,
          },
          followerCount: 0,
          aboutMe: "",
        },
      },
      {
        id: 122841,
        mediaType: "audio",
        mediaSubType: 3,
        duration: 173,
        uploadDate: "2023-03-18T06:14:09.362355",
        href: "https://pixabay.com/music/solo-guitar-the-beat-of-nature-122841/",
        sources: {
          src: "https://cdn.pixabay.com/audio/2022/10/14/audio_9939f792cb.mp3",
          waveformUrl: "/music/122841/waveform.json",
          thumbnailUrl: "",
          thumbnailOrientation: "portrait",
          downloadUrl:
            "https://cdn.pixabay.com/download/audio/2022/10/14/audio_9939f792cb.mp3?filename=the-beat-of-nature-122841.mp3",
        },
        alt: "Acoustic, Acoustic Guitar, Indie, Folk",
        title: null,
        description:
          "Acoustic, Acoustic Guitar, Indie, Folk, Acoustic Folk, Relax",
        name: "The Beat of Nature",
        nsfw: false,
        tagLinks:
          '<a href="/music/search/acoustic/">acoustic</a> <a href="/music/search/acoustic%20guitar/">acoustic guitar</a>',
        likeCount: 1517,
        likeHref: "/accounts/like/audio/122841/",
        commentCount: 103,
        commentHref: "/music/solo-guitar-the-beat-of-nature-122841/#comments",
        contentIdCertificateUrl: "/music/122841/license/",
        attributionHtml:
          'Music by <a href="https://pixabay.com/users/olexy-25300778/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=122841">Olexy</a> from <a href="https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=122841">Pixabay</a>',
        vector: false,
        isEditorsChoice: true,
        isLowQuality: false,
        qualityStatus: 5,
        rating: 9,
        user: {
          id: 25300778,
          username: "Olexy",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2022/06/18/11-10-07-302_96x96.jpg",
          profileUrl: "/users/olexy-25300778/",
          socialLinks: [],
          donation: { paypal: "X4ZFBYPN472VL", method: 2 },
          followerCount: 0,
          aboutMe: "",
        },
      },
      {
        id: 122844,
        mediaType: "audio",
        mediaSubType: 3,
        duration: 177,
        uploadDate: "2023-03-18T06:14:09.362919",
        href: "https://pixabay.com/music/beats-cinim-brainfluid-122844/",
        sources: {
          src: "https://cdn.pixabay.com/audio/2022/10/14/audio_84b5738b17.mp3",
          waveformUrl: "/music/122844/waveform.json",
          thumbnailUrl:
            "https://cdn.pixabay.com/audio/2022/10/14/13-08-36-813_200x200.png",
          thumbnailOrientation: "portrait",
          downloadUrl:
            "https://cdn.pixabay.com/download/audio/2022/10/14/audio_84b5738b17.mp3?filename=cinim-brainfluid-122844.mp3",
        },
        alt: "Bass, Electronic, Glitch, Beats",
        title: null,
        description:
          "Bass, Electronic, Glitch, Beats, Experimental, Braindance",
        name: "CINIM - Brainfluid",
        nsfw: false,
        tagLinks:
          '<a href="/music/search/bass/">bass</a> <a href="/music/search/electronic/">electronic</a> <a href="/music/search/glitch/">glitch</a>',
        likeCount: 227,
        likeHref: "/accounts/like/audio/122844/",
        commentCount: 15,
        commentHref: "/music/beats-cinim-brainfluid-122844/#comments",
        contentIdCertificateUrl: null,
        attributionHtml:
          'Music by <a href="https://pixabay.com/users/cinim-30594952/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=122844">CINIM</a> from <a href="https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=122844">Pixabay</a>',
        vector: false,
        isEditorsChoice: true,
        isLowQuality: false,
        qualityStatus: 5,
        rating: 9,
        user: {
          id: 30594952,
          username: "CINIM",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2023/01/16/14-01-23-167_96x96.png",
          profileUrl: "/users/cinim-30594952/",
          socialLinks: [],
          donation: { paypal: "SV3DRESCY3CCN", method: 2 },
          followerCount: 0,
          aboutMe: "",
        },
      },
      {
        id: 122592,
        mediaType: "audio",
        mediaSubType: 3,
        duration: 208,
        uploadDate: "2023-03-18T06:14:09.363480",
        href: "https://pixabay.com/music/beats-weeknds-122592/",
        sources: {
          src: "https://cdn.pixabay.com/audio/2022/10/12/audio_061cead49a.mp3",
          waveformUrl: "/music/122592/waveform.json",
          thumbnailUrl:
            "https://cdn.pixabay.com/audio/2022/10/12/09-28-04-865_200x200.jpg",
          thumbnailOrientation: "portrait",
          downloadUrl:
            "https://cdn.pixabay.com/download/audio/2022/10/12/audio_061cead49a.mp3?filename=weeknds-122592.mp3",
        },
        alt: "Thanks for listening - please subscribe to my YouTube channel: https://www.youtube.com/c/Dayfox/featured Coffee ? Donations: contact@dayfox.de",
        title: null,
        description:
          "Background, Corporate, Promo, Soft, Tutorial, Vlog, Vlogging",
        name: "Weeknds",
        nsfw: false,
        tagLinks:
          '<a href="/music/search/background/">background</a> <a href="/music/search/corporate/">corporate</a>',
        likeCount: 746,
        likeHref: "/accounts/like/audio/122592/",
        commentCount: 29,
        commentHref: "/music/beats-weeknds-122592/#comments",
        contentIdCertificateUrl: "/music/122592/license/",
        attributionHtml:
          'Music by <a href="https://pixabay.com/users/dayfox-29184718/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=122592">DayFox</a> from <a href="https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=122592">Pixabay</a>',
        vector: false,
        isEditorsChoice: true,
        isLowQuality: false,
        qualityStatus: 5,
        rating: 9,
        user: {
          id: 29184718,
          username: "DayFox",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2022/08/10/16-56-20-687_96x96.jpg",
          profileUrl: "/users/dayfox-29184718/",
          socialLinks: [],
          donation: { paypal: "contact@dayfox.de", method: 2 },
          followerCount: 0,
          aboutMe: "",
        },
      },
      {
        id: 121791,
        mediaType: "audio",
        mediaSubType: 3,
        duration: 73,
        uploadDate: "2023-03-18T06:14:09.364054",
        href: "https://pixabay.com/music/future-bass-powerful-beat-121791/",
        sources: {
          src: "https://cdn.pixabay.com/audio/2022/10/05/audio_686ddcce85.mp3",
          waveformUrl: "/music/121791/waveform.json",
          thumbnailUrl:
            "https://cdn.pixabay.com/audio/2022/10/05/02-12-02-660_200x200.jpeg",
          thumbnailOrientation: "portrait",
          downloadUrl:
            "https://cdn.pixabay.com/download/audio/2022/10/05/audio_686ddcce85.mp3?filename=powerful-beat-121791.mp3",
        },
        alt: "Abstract, Advertising, Beat, City",
        title: null,
        description: "Abstract, Advertising, Beat, City, Driving, Dynamic",
        name: "Powerful Beat",
        nsfw: false,
        tagLinks:
          '<a href="/music/search/abstract/">abstract</a> <a href="/music/search/advertising/">advertising</a>',
        likeCount: 1079,
        likeHref: "/accounts/like/audio/121791/",
        commentCount: 0,
        commentHref: "/music/future-bass-powerful-beat-121791/#comments",
        contentIdCertificateUrl: "/music/121791/license/",
        attributionHtml:
          'Music by <a href="https://pixabay.com/users/penguinmusic-24940186/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=121791">penguinmusic</a> from <a href="https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=121791">Pixabay</a>',
        vector: false,
        isEditorsChoice: true,
        isLowQuality: false,
        qualityStatus: 5,
        rating: 9,
        user: {
          id: 24940186,
          username: "penguinmusic",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2021/12/27/04-06-14-169_96x96.png",
          profileUrl: "/users/penguinmusic-24940186/",
          socialLinks: [],
          donation: { paypal: "creo.musick@gmail.com", method: 2 },
          followerCount: 0,
          aboutMe: "",
        },
      },
    ],
    order: "ec",
    bannerMedia: {
      small: "https://cdn.pixabay.com/index/2022/10/11/19-18-22-858_640.jpg",
      medium:
        "https://cdn.pixabay.com/index/2022/10/11/19-18-22-858_1440x550.jpg",
      large:
        "https://cdn.pixabay.com/index/2022/10/11/19-18-22-858_1920x550.jpg",
    },
    bannerUser: "Icons8_team",
    bannerUserUrl: "/photos/headphones-blue-pink-pastel-colors-3435888/",
    popularSearches: [
      "background music",
      "relaxing",
      "birthday",
      "song",
      "instrumental",
      "beats",
      "vlog music",
      "sad",
      "upbeat",
      "audio",
      "happy",
      "english",
    ],
    safesearch: "",
    viewMoreUrl: "/music/search/?order=ec",
    faqUrl: "/service/faq/",
    featuredArtists: [
      {
        artist: {
          id: 11989248,
          username: "RomanSenykMusic",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2023/01/11/22-32-15-627_96x96.png",
          profileUrl: "/users/romansenykmusic-11989248/",
          socialLinks: [],
          donation: null,
          followerCount: 0,
          aboutMe: "",
        },
        media: [
          {
            id: 124618,
            mediaType: "audio",
            mediaSubType: 3,
            duration: null,
            uploadDate: "2023-03-18T06:14:09.578737",
            href: "https://pixabay.com/music/successful-business-124618/",
            sources: {
              src: "https://cdn.pixabay.com/audio/2022/10/31/audio_6583657741.mp3",
              waveformUrl: "/music/124618/waveform.json",
              thumbnailUrl:
                "https://cdn.pixabay.com/audio/2022/10/31/16-17-25-644_200x200.png",
              thumbnailOrientation: "portrait",
              downloadUrl:
                "https://cdn.pixabay.com/download/audio/2022/10/31/audio_6583657741.mp3?filename=successful-business-124618.mp3",
            },
            alt: "",
            title: null,
            description: "",
            name: "Successful Business",
            nsfw: false,
            tagLinks: "",
            likeCount: 0,
            likeHref: "/accounts/like/audio/124618/",
            commentCount: 0,
            commentHref: "/music/successful-business-124618/#comments",
            contentIdCertificateUrl: null,
            attributionHtml:
              'Music by <a href="https://pixabay.com/users/romansenykmusic-11989248/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=124618">Roman Senyk</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=124618">Pixabay</a>',
            vector: false,
            isEditorsChoice: false,
            isLowQuality: false,
            qualityStatus: 0,
            rating: null,
          },
        ],
      },
      {
        artist: {
          id: 34071953,
          username: "orangery",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2023/03/02/13-35-19-515_96x96.jpg",
          profileUrl: "/users/orangery-34071953/",
          socialLinks: [],
          donation: null,
          followerCount: 0,
          aboutMe: "",
        },
        media: [
          {
            id: 142569,
            mediaType: "audio",
            mediaSubType: 3,
            duration: null,
            uploadDate: "2023-03-18T06:14:09.579234",
            href: "https://pixabay.com/music/acoustic-group-coniferous-forest-142569/",
            sources: {
              src: "https://cdn.pixabay.com/audio/2023/03/14/audio_676747013a.mp3",
              waveformUrl: "/music/142569/waveform.json",
              thumbnailUrl: "",
              thumbnailOrientation: "portrait",
              downloadUrl:
                "https://cdn.pixabay.com/download/audio/2023/03/14/audio_676747013a.mp3?filename=coniferous-forest-142569.mp3",
            },
            alt: "",
            title: null,
            description: "",
            name: "Coniferous forest",
            nsfw: false,
            tagLinks: "",
            likeCount: 0,
            likeHref: "/accounts/like/audio/142569/",
            commentCount: 0,
            commentHref:
              "/music/acoustic-group-coniferous-forest-142569/#comments",
            contentIdCertificateUrl: null,
            attributionHtml:
              'Music by <a href="https://pixabay.com/users/orangery-34071953/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=142569">orangery</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=142569">Pixabay</a>',
            vector: false,
            isEditorsChoice: false,
            isLowQuality: false,
            qualityStatus: 0,
            rating: null,
          },
        ],
      },
      {
        artist: {
          id: 26079283,
          username: "ComaStudio",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2022/03/10/11-06-25-684_96x96.jpg",
          profileUrl: "/users/comastudio-26079283/",
          socialLinks: [],
          donation: null,
          followerCount: 0,
          aboutMe: "",
        },
        media: [
          {
            id: 121475,
            mediaType: "audio",
            mediaSubType: 3,
            duration: null,
            uploadDate: "2023-03-18T06:14:09.579635",
            href: "https://pixabay.com/music/stylish-rock-trap-beat-121475/",
            sources: {
              src: "https://cdn.pixabay.com/audio/2022/10/01/audio_4b87ef7fde.mp3",
              waveformUrl: "/music/121475/waveform.json",
              thumbnailUrl: "",
              thumbnailOrientation: "portrait",
              downloadUrl:
                "https://cdn.pixabay.com/download/audio/2022/10/01/audio_4b87ef7fde.mp3?filename=stylish-rock-trap-beat-121475.mp3",
            },
            alt: "",
            title: null,
            description: "",
            name: "Stylish Rock Trap Beat",
            nsfw: false,
            tagLinks: "",
            likeCount: 0,
            likeHref: "/accounts/like/audio/121475/",
            commentCount: 0,
            commentHref: "/music/stylish-rock-trap-beat-121475/#comments",
            contentIdCertificateUrl: null,
            attributionHtml:
              'Music by <a href="https://pixabay.com/users/comastudio-26079283/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=121475">ComaStudio</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=121475">Pixabay</a>',
            vector: false,
            isEditorsChoice: false,
            isLowQuality: false,
            qualityStatus: 0,
            rating: null,
          },
        ],
      },
      {
        artist: {
          id: 27005420,
          username: "AudioCoffee",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2023/02/15/12-18-08-6_96x96.png",
          profileUrl: "/users/audiocoffee-27005420/",
          socialLinks: [],
          donation: null,
          followerCount: 0,
          aboutMe: "",
        },
        media: [
          {
            id: 110769,
            mediaType: "audio",
            mediaSubType: 3,
            duration: null,
            uploadDate: "2023-03-18T06:14:09.580027",
            href: "https://pixabay.com/music/ambient-hip-hop-background-music-for-videos-110769/",
            sources: {
              src: "https://cdn.pixabay.com/audio/2022/05/07/audio_f266b00c17.mp3",
              waveformUrl: "/music/110769/waveform.json",
              thumbnailUrl:
                "https://cdn.pixabay.com/audio/2022/05/07/11-12-46-180_200x200.jpg",
              thumbnailOrientation: "portrait",
              downloadUrl:
                "https://cdn.pixabay.com/download/audio/2022/05/07/audio_f266b00c17.mp3?filename=ambient-hip-hop-background-music-for-videos-110769.mp3",
            },
            alt: "",
            title: null,
            description: "",
            name: "Ambient Hip-Hop / Background Music For Videos",
            nsfw: false,
            tagLinks: "",
            likeCount: 0,
            likeHref: "/accounts/like/audio/110769/",
            commentCount: 0,
            commentHref:
              "/music/ambient-hip-hop-background-music-for-videos-110769/#comments",
            contentIdCertificateUrl: null,
            attributionHtml:
              'Music by <a href="https://pixabay.com/users/audiocoffee-27005420/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=110769">Denys Kyshchuk</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=110769">Pixabay</a>',
            vector: false,
            isEditorsChoice: false,
            isLowQuality: false,
            qualityStatus: 0,
            rating: null,
          },
        ],
      },
      {
        artist: {
          id: 17430502,
          username: "RelaxingTime",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2020/07/14/11-26-10-530_96x96.jpg",
          profileUrl: "/users/relaxingtime-17430502/",
          socialLinks: [],
          donation: null,
          followerCount: 0,
          aboutMe: "",
        },
        media: [
          {
            id: 136203,
            mediaType: "audio",
            mediaSubType: 3,
            duration: null,
            uploadDate: "2023-03-18T06:14:09.580442",
            href: "https://pixabay.com/music/relaxing-music-vol16-136203/",
            sources: {
              src: "https://cdn.pixabay.com/audio/2023/01/22/audio_6d454831cf.mp3",
              waveformUrl: "/music/136203/waveform.json",
              thumbnailUrl: "",
              thumbnailOrientation: "portrait",
              downloadUrl:
                "https://cdn.pixabay.com/download/audio/2023/01/22/audio_6d454831cf.mp3?filename=relaxing-music-vol16-136203.mp3",
            },
            alt: "",
            title: null,
            description: "",
            name: "Relaxing Music Vol.16",
            nsfw: false,
            tagLinks: "",
            likeCount: 0,
            likeHref: "/accounts/like/audio/136203/",
            commentCount: 0,
            commentHref: "/music/relaxing-music-vol16-136203/#comments",
            contentIdCertificateUrl: null,
            attributionHtml:
              'Music by <a href="https://pixabay.com/users/relaxingtime-17430502/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=136203">Piotr Witowski</a> from <a href="https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=136203">Pixabay</a>',
            vector: false,
            isEditorsChoice: false,
            isLowQuality: false,
            qualityStatus: 0,
            rating: null,
          },
        ],
      },
      {
        artist: {
          id: 30064790,
          username: "SoulProdMusic",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2022/09/20/21-47-25-136_96x96.jpg",
          profileUrl: "/users/soulprodmusic-30064790/",
          socialLinks: [],
          donation: null,
          followerCount: 0,
          aboutMe: "",
        },
        media: [
          {
            id: 129281,
            mediaType: "audio",
            mediaSubType: 3,
            duration: null,
            uploadDate: "2023-03-18T06:14:09.580926",
            href: "https://pixabay.com/music/dawn-129281/",
            sources: {
              src: "https://cdn.pixabay.com/audio/2022/12/13/audio_3eb782d5f9.mp3",
              waveformUrl: "/music/129281/waveform.json",
              thumbnailUrl:
                "https://cdn.pixabay.com/audio/2022/12/13/19-09-20-819_200x200.jpg",
              thumbnailOrientation: "portrait",
              downloadUrl:
                "https://cdn.pixabay.com/download/audio/2022/12/13/audio_3eb782d5f9.mp3?filename=dawn-129281.mp3",
            },
            alt: "",
            title: null,
            description: "",
            name: "Dawn",
            nsfw: false,
            tagLinks: "",
            likeCount: 0,
            likeHref: "/accounts/like/audio/129281/",
            commentCount: 0,
            commentHref: "/music/dawn-129281/#comments",
            contentIdCertificateUrl: null,
            attributionHtml:
              'Music by <a href="https://pixabay.com/users/soulprodmusic-30064790/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=129281">Oleg Fedak</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=129281">Pixabay</a>',
            vector: false,
            isEditorsChoice: false,
            isLowQuality: false,
            qualityStatus: 0,
            rating: null,
          },
        ],
      },
      {
        artist: {
          id: 24686998,
          username: "Playsound",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2021/12/06/13-59-30-385_96x96.jpg",
          profileUrl: "/users/playsound-24686998/",
          socialLinks: [],
          donation: null,
          followerCount: 0,
          aboutMe: "",
        },
        media: [
          {
            id: 124538,
            mediaType: "audio",
            mediaSubType: 3,
            duration: null,
            uploadDate: "2023-03-18T06:14:09.581367",
            href: "https://pixabay.com/music/hip-hop-background-124538/",
            sources: {
              src: "https://cdn.pixabay.com/audio/2022/10/31/audio_295747e375.mp3",
              waveformUrl: "/music/124538/waveform.json",
              thumbnailUrl:
                "https://cdn.pixabay.com/audio/2022/10/31/10-06-43-158_200x200.jpg",
              thumbnailOrientation: "portrait",
              downloadUrl:
                "https://cdn.pixabay.com/download/audio/2022/10/31/audio_295747e375.mp3?filename=hip-hop-background-124538.mp3",
            },
            alt: "",
            title: null,
            description: "",
            name: "Hip Hop Background",
            nsfw: false,
            tagLinks: "",
            likeCount: 0,
            likeHref: "/accounts/like/audio/124538/",
            commentCount: 0,
            commentHref: "/music/hip-hop-background-124538/#comments",
            contentIdCertificateUrl: null,
            attributionHtml:
              'Music by <a href="https://pixabay.com/users/playsound-24686998/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=124538">Playsound</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=124538">Pixabay</a>',
            vector: false,
            isEditorsChoice: false,
            isLowQuality: false,
            qualityStatus: 0,
            rating: null,
          },
        ],
      },
      {
        artist: {
          id: 3433550,
          username: "FASSounds",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2022/05/27/23-55-29-489_96x96.jpg",
          profileUrl: "/users/fassounds-3433550/",
          socialLinks: [],
          donation: null,
          followerCount: 0,
          aboutMe: "",
        },
        media: [
          {
            id: 112776,
            mediaType: "audio",
            mediaSubType: 3,
            duration: null,
            uploadDate: "2023-03-18T06:14:09.581766",
            href: "https://pixabay.com/music/sunset-rider-112776/",
            sources: {
              src: "https://cdn.pixabay.com/audio/2022/06/06/audio_5fa7759b68.mp3",
              waveformUrl: "/music/112776/waveform.json",
              thumbnailUrl:
                "https://cdn.pixabay.com/audio/2022/06/06/01-57-18-509_200x200.jpg",
              thumbnailOrientation: "portrait",
              downloadUrl:
                "https://cdn.pixabay.com/download/audio/2022/06/06/audio_5fa7759b68.mp3?filename=sunset-rider-112776.mp3",
            },
            alt: "",
            title: null,
            description: "",
            name: "Sunset Rider",
            nsfw: false,
            tagLinks: "",
            likeCount: 0,
            likeHref: "/accounts/like/audio/112776/",
            commentCount: 0,
            commentHref: "/music/sunset-rider-112776/#comments",
            contentIdCertificateUrl: null,
            attributionHtml:
              'Music by <a href="https://pixabay.com/users/fassounds-3433550/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=112776">FASSounds</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=112776">Pixabay</a>',
            vector: false,
            isEditorsChoice: false,
            isLowQuality: false,
            qualityStatus: 0,
            rating: null,
          },
        ],
      },
      {
        artist: {
          id: 32752748,
          username: "teodholina",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2023/02/22/22-56-18-459_96x96.jpg",
          profileUrl: "/users/teodholina-32752748/",
          socialLinks: [],
          donation: null,
          followerCount: 0,
          aboutMe: "",
        },
        media: [
          {
            id: 142092,
            mediaType: "audio",
            mediaSubType: 3,
            duration: null,
            uploadDate: "2023-03-18T06:14:09.582154",
            href: "https://pixabay.com/music/game-setting-fantasy-142092/",
            sources: {
              src: "https://cdn.pixabay.com/audio/2023/03/10/audio_d61d9797e0.mp3",
              waveformUrl: "/music/142092/waveform.json",
              thumbnailUrl:
                "https://cdn.pixabay.com/audio/2023/03/10/15-40-26-117_200x200.jpg",
              thumbnailOrientation: "portrait",
              downloadUrl:
                "https://cdn.pixabay.com/download/audio/2023/03/10/audio_d61d9797e0.mp3?filename=game-setting-fantasy-142092.mp3",
            },
            alt: "",
            title: null,
            description: "",
            name: "game setting fantasy",
            nsfw: false,
            tagLinks: "",
            likeCount: 0,
            likeHref: "/accounts/like/audio/142092/",
            commentCount: 0,
            commentHref: "/music/game-setting-fantasy-142092/#comments",
            contentIdCertificateUrl: null,
            attributionHtml:
              'Music by <a href="https://pixabay.com/users/teodholina-32752748/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=142092">teodholina</a> from <a href="https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=142092">Pixabay</a>',
            vector: false,
            isEditorsChoice: false,
            isLowQuality: false,
            qualityStatus: 0,
            rating: null,
          },
        ],
      },
      {
        artist: {
          id: 33612407,
          username: "Alex_Kizenkov",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2023/03/09/14-24-53-643_96x96.png",
          profileUrl: "/users/alex_kizenkov-33612407/",
          socialLinks: [],
          donation: null,
          followerCount: 0,
          aboutMe: "",
        },
        media: [
          {
            id: 141948,
            mediaType: "audio",
            mediaSubType: 3,
            duration: null,
            uploadDate: "2023-03-18T06:14:09.582533",
            href: "https://pixabay.com/music/lost-in-the-shadows-trap-141948/",
            sources: {
              src: "https://cdn.pixabay.com/audio/2023/03/09/audio_fd1b46415e.mp3",
              waveformUrl: "/music/141948/waveform.json",
              thumbnailUrl:
                "https://cdn.pixabay.com/audio/2023/03/09/08-38-37-666_200x200.png",
              thumbnailOrientation: "portrait",
              downloadUrl:
                "https://cdn.pixabay.com/download/audio/2023/03/09/audio_fd1b46415e.mp3?filename=lost-in-the-shadows-trap-141948.mp3",
            },
            alt: "",
            title: null,
            description: "",
            name: "Lost In The Shadows (Trap)",
            nsfw: false,
            tagLinks: "",
            likeCount: 0,
            likeHref: "/accounts/like/audio/141948/",
            commentCount: 0,
            commentHref: "/music/lost-in-the-shadows-trap-141948/#comments",
            contentIdCertificateUrl: null,
            attributionHtml:
              'Music by <a href="https://pixabay.com/users/alex_kizenkov-33612407/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=141948">Alex_Kizenkov</a> from <a href="https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=141948">Pixabay</a>',
            vector: false,
            isEditorsChoice: false,
            isLowQuality: false,
            qualityStatus: 0,
            rating: null,
          },
        ],
      },
      {
        artist: {
          id: 34079374,
          username: "ADMusicFreeMusic",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2023/03/02/18-32-47-842_96x96.png",
          profileUrl: "/users/admusicfreemusic-34079374/",
          socialLinks: [],
          donation: null,
          followerCount: 0,
          aboutMe: "",
        },
        media: [
          {
            id: 141289,
            mediaType: "audio",
            mediaSubType: 3,
            duration: null,
            uploadDate: "2023-03-18T06:14:09.582909",
            href: "https://pixabay.com/music/main-title-one-last-time-141289/",
            sources: {
              src: "https://cdn.pixabay.com/audio/2023/03/02/audio_d3796f044f.mp3",
              waveformUrl: "/music/141289/waveform.json",
              thumbnailUrl:
                "https://cdn.pixabay.com/audio/2023/03/02/18-35-27-99_200x200.png",
              thumbnailOrientation: "portrait",
              downloadUrl:
                "https://cdn.pixabay.com/download/audio/2023/03/02/audio_d3796f044f.mp3?filename=one-last-time-141289.mp3",
            },
            alt: "",
            title: null,
            description: "",
            name: "One Last Time",
            nsfw: false,
            tagLinks: "",
            likeCount: 0,
            likeHref: "/accounts/like/audio/141289/",
            commentCount: 0,
            commentHref: "/music/main-title-one-last-time-141289/#comments",
            contentIdCertificateUrl: null,
            attributionHtml:
              'Music by <a href="https://pixabay.com/users/admusicfreemusic-34079374/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=141289">Adriel Dos Santos</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=141289">Pixabay</a>',
            vector: false,
            isEditorsChoice: false,
            isLowQuality: false,
            qualityStatus: 0,
            rating: null,
          },
        ],
      },
      {
        artist: {
          id: 3616498,
          username: "The_Mountain",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2022/12/17/06-41-28-939_96x96.jpg",
          profileUrl: "/users/the_mountain-3616498/",
          socialLinks: [],
          donation: null,
          followerCount: 0,
          aboutMe: "",
        },
        media: [
          {
            id: 131395,
            mediaType: "audio",
            mediaSubType: 3,
            duration: null,
            uploadDate: "2023-03-18T06:14:09.583286",
            href: "https://pixabay.com/music/the-corporate-background-131395/",
            sources: {
              src: "https://cdn.pixabay.com/audio/2022/12/28/audio_2ae627cb68.mp3",
              waveformUrl: "/music/131395/waveform.json",
              thumbnailUrl:
                "https://cdn.pixabay.com/audio/2022/12/28/17-13-06-787_200x200.png",
              thumbnailOrientation: "portrait",
              downloadUrl:
                "https://cdn.pixabay.com/download/audio/2022/12/28/audio_2ae627cb68.mp3?filename=the-corporate-background-131395.mp3",
            },
            alt: "",
            title: null,
            description: "",
            name: "The Corporate Background",
            nsfw: false,
            tagLinks: "",
            likeCount: 0,
            likeHref: "/accounts/like/audio/131395/",
            commentCount: 0,
            commentHref: "/music/the-corporate-background-131395/#comments",
            contentIdCertificateUrl: null,
            attributionHtml:
              'Music by <a href="https://pixabay.com/users/the_mountain-3616498/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=131395">Dmitrii Kolesnikov</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=131395">Pixabay</a>',
            vector: false,
            isEditorsChoice: false,
            isLowQuality: false,
            qualityStatus: 0,
            rating: null,
          },
        ],
      },
      {
        artist: {
          id: 27716187,
          username: "ArtMusic",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2023/01/30/04-40-45-929_96x96.jpg",
          profileUrl: "/users/artmusic-27716187/",
          socialLinks: [],
          donation: null,
          followerCount: 0,
          aboutMe: "",
        },
        media: [
          {
            id: 137209,
            mediaType: "audio",
            mediaSubType: 3,
            duration: null,
            uploadDate: "2023-03-18T06:14:09.583691",
            href: "https://pixabay.com/music/spring-cinematic-guitar-137209/",
            sources: {
              src: "https://cdn.pixabay.com/audio/2023/01/30/audio_6981f635bf.mp3",
              waveformUrl: "/music/137209/waveform.json",
              thumbnailUrl: "",
              thumbnailOrientation: "portrait",
              downloadUrl:
                "https://cdn.pixabay.com/download/audio/2023/01/30/audio_6981f635bf.mp3?filename=spring-cinematic-guitar-137209.mp3",
            },
            alt: "",
            title: null,
            description: "",
            name: "Spring (Cinematic Guitar)",
            nsfw: false,
            tagLinks: "",
            likeCount: 0,
            likeHref: "/accounts/like/audio/137209/",
            commentCount: 0,
            commentHref: "/music/spring-cinematic-guitar-137209/#comments",
            contentIdCertificateUrl: null,
            attributionHtml:
              'Music by <a href="https://pixabay.com/users/artmusic-27716187/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=137209">Vitalii Korol</a> from <a href="https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=137209">Pixabay</a>',
            vector: false,
            isEditorsChoice: false,
            isLowQuality: false,
            qualityStatus: 0,
            rating: null,
          },
        ],
      },
      {
        artist: {
          id: 2073170,
          username: "StudioKolomna",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2022/07/04/12-42-22-460_96x96.png",
          profileUrl: "/users/studiokolomna-2073170/",
          socialLinks: [],
          donation: null,
          followerCount: 0,
          aboutMe: "",
        },
        media: [
          {
            id: 114327,
            mediaType: "audio",
            mediaSubType: 3,
            duration: null,
            uploadDate: "2023-03-18T06:14:09.584108",
            href: "https://pixabay.com/music/epic-dramatic-action-114327/",
            sources: {
              src: "https://cdn.pixabay.com/audio/2022/07/04/audio_5d96303191.mp3",
              waveformUrl: "/music/114327/waveform.json",
              thumbnailUrl:
                "https://cdn.pixabay.com/audio/2022/07/04/14-09-34-508_200x200.png",
              thumbnailOrientation: "portrait",
              downloadUrl:
                "https://cdn.pixabay.com/download/audio/2022/07/04/audio_5d96303191.mp3?filename=epic-dramatic-action-114327.mp3",
            },
            alt: "",
            title: null,
            description: "",
            name: "Epic Dramatic Action",
            nsfw: false,
            tagLinks: "",
            likeCount: 0,
            likeHref: "/accounts/like/audio/114327/",
            commentCount: 0,
            commentHref: "/music/epic-dramatic-action-114327/#comments",
            contentIdCertificateUrl: null,
            attributionHtml:
              'Music by <a href="https://pixabay.com/users/studiokolomna-2073170/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=114327">Denis Maksimov</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=114327">Pixabay</a>',
            vector: false,
            isEditorsChoice: false,
            isLowQuality: false,
            qualityStatus: 0,
            rating: null,
          },
        ],
      },
      {
        artist: {
          id: 27049680,
          username: "Ashot-Danielyan-Composer",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2022/05/01/01-22-12-683_96x96.jpg",
          profileUrl: "/users/ashot-danielyan-composer-27049680/",
          socialLinks: [],
          donation: null,
          followerCount: 0,
          aboutMe: "",
        },
        media: [
          {
            id: 115093,
            mediaType: "audio",
            mediaSubType: 3,
            duration: null,
            uploadDate: "2023-03-18T06:14:09.584530",
            href: "https://pixabay.com/music/serious-melancholic-sad-piano-115093/",
            sources: {
              src: "https://cdn.pixabay.com/audio/2022/07/15/audio_ae3395baad.mp3",
              waveformUrl: "/music/115093/waveform.json",
              thumbnailUrl:
                "https://cdn.pixabay.com/audio/2022/12/28/01-48-31-297_200x200.jpg",
              thumbnailOrientation: "portrait",
              downloadUrl:
                "https://cdn.pixabay.com/download/audio/2022/07/15/audio_ae3395baad.mp3?filename=serious-melancholic-sad-piano-115093.mp3",
            },
            alt: "",
            title: null,
            description: "",
            name: "Serious Melancholic Sad Piano",
            nsfw: false,
            tagLinks: "",
            likeCount: 0,
            likeHref: "/accounts/like/audio/115093/",
            commentCount: 0,
            commentHref:
              "/music/serious-melancholic-sad-piano-115093/#comments",
            contentIdCertificateUrl: null,
            attributionHtml:
              'Music by <a href="https://pixabay.com/users/ashot-danielyan-composer-27049680/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=115093">Ashot Danielyan</a> from <a href="https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=115093">Pixabay</a>',
            vector: false,
            isEditorsChoice: false,
            isLowQuality: false,
            qualityStatus: 0,
            rating: null,
          },
        ],
      },
      {
        artist: {
          id: 22579021,
          username: "Lesfm",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2022/06/18/09-26-46-83_96x96.png",
          profileUrl: "/users/lesfm-22579021/",
          socialLinks: [],
          donation: null,
          followerCount: 0,
          aboutMe: "",
        },
        media: [
          {
            id: 5877,
            mediaType: "audio",
            mediaSubType: 3,
            duration: null,
            uploadDate: "2023-03-18T06:14:09.584958",
            href: "https://pixabay.com/music/energetic-and-upbeat-indie-rock-positive-loop-2-30s-5877/",
            sources: {
              src: "https://cdn.pixabay.com/audio/2021/08/02/audio_80b88ec598.mp3",
              waveformUrl: "/music/5877/waveform.json",
              thumbnailUrl: "",
              thumbnailOrientation: "portrait",
              downloadUrl:
                "https://cdn.pixabay.com/download/audio/2021/08/02/audio_80b88ec598.mp3?filename=energetic-and-upbeat-indie-rock-positive-loop-2-30s-5877.mp3",
            },
            alt: "",
            title: null,
            description: "",
            name: "Energetic and Upbeat Indie Rock Positive (Loop 2 30s)",
            nsfw: false,
            tagLinks: "",
            likeCount: 0,
            likeHref: "/accounts/like/audio/5877/",
            commentCount: 0,
            commentHref:
              "/music/energetic-and-upbeat-indie-rock-positive-loop-2-30s-5877/#comments",
            contentIdCertificateUrl: null,
            attributionHtml:
              'Music by <a href="https://pixabay.com/users/lesfm-22579021/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=5877">Oleksii Kaplunskyi</a> from <a href="https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=5877">Pixabay</a>',
            vector: false,
            isEditorsChoice: false,
            isLowQuality: false,
            qualityStatus: 0,
            rating: null,
          },
        ],
      },
      {
        artist: {
          id: 26977400,
          username: "AlexiAction",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2022/04/24/14-49-29-962_96x96.jpg",
          profileUrl: "/users/alexiaction-26977400/",
          socialLinks: [],
          donation: null,
          followerCount: 0,
          aboutMe: "",
        },
        media: [
          {
            id: 139061,
            mediaType: "audio",
            mediaSubType: 3,
            duration: null,
            uploadDate: "2023-03-18T06:14:09.585378",
            href: "https://pixabay.com/music/asia-oriental-logo-139061/",
            sources: {
              src: "https://cdn.pixabay.com/audio/2023/02/13/audio_c96898a8c7.mp3",
              waveformUrl: "/music/139061/waveform.json",
              thumbnailUrl:
                "https://cdn.pixabay.com/audio/2023/02/13/02-47-57-228_200x200.png",
              thumbnailOrientation: "portrait",
              downloadUrl:
                "https://cdn.pixabay.com/download/audio/2023/02/13/audio_c96898a8c7.mp3?filename=asia-oriental-logo-139061.mp3",
            },
            alt: "",
            title: null,
            description: "",
            name: "Asia Oriental Logo",
            nsfw: false,
            tagLinks: "",
            likeCount: 0,
            likeHref: "/accounts/like/audio/139061/",
            commentCount: 0,
            commentHref: "/music/asia-oriental-logo-139061/#comments",
            contentIdCertificateUrl: null,
            attributionHtml:
              'Music by <a href="https://pixabay.com/users/alexiaction-26977400/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=139061">Alexi Action</a> from <a href="https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=139061">Pixabay</a>',
            vector: false,
            isEditorsChoice: false,
            isLowQuality: false,
            qualityStatus: 0,
            rating: null,
          },
        ],
      },
      {
        artist: {
          id: 24940186,
          username: "penguinmusic",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2021/12/27/04-06-14-169_96x96.png",
          profileUrl: "/users/penguinmusic-24940186/",
          socialLinks: [],
          donation: null,
          followerCount: 0,
          aboutMe: "",
        },
        media: [
          {
            id: 121793,
            mediaType: "audio",
            mediaSubType: 3,
            duration: null,
            uploadDate: "2023-03-18T06:14:09.585760",
            href: "https://pixabay.com/music/this-is-future-bass-121793/",
            sources: {
              src: "https://cdn.pixabay.com/audio/2022/10/05/audio_bbda314481.mp3",
              waveformUrl: "/music/121793/waveform.json",
              thumbnailUrl:
                "https://cdn.pixabay.com/audio/2022/10/05/02-01-50-625_200x200.jpeg",
              thumbnailOrientation: "portrait",
              downloadUrl:
                "https://cdn.pixabay.com/download/audio/2022/10/05/audio_bbda314481.mp3?filename=this-is-future-bass-121793.mp3",
            },
            alt: "",
            title: null,
            description: "",
            name: "This is Future Bass",
            nsfw: false,
            tagLinks: "",
            likeCount: 0,
            likeHref: "/accounts/like/audio/121793/",
            commentCount: 0,
            commentHref: "/music/this-is-future-bass-121793/#comments",
            contentIdCertificateUrl: null,
            attributionHtml:
              'Music by <a href="https://pixabay.com/users/penguinmusic-24940186/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=121793">Oleksandr Stepanov</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=121793">Pixabay</a>',
            vector: false,
            isEditorsChoice: false,
            isLowQuality: false,
            qualityStatus: 0,
            rating: null,
          },
        ],
      },
      {
        artist: {
          id: 34040748,
          username: "Monument_Music",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2023/03/01/12-06-18-805_96x96.jpeg",
          profileUrl: "/users/monument_music-34040748/",
          socialLinks: [],
          donation: null,
          followerCount: 0,
          aboutMe: "",
        },
        media: [
          {
            id: 141357,
            mediaType: "audio",
            mediaSubType: 3,
            duration: null,
            uploadDate: "2023-03-18T06:14:09.586142",
            href: "https://pixabay.com/music/news-time-141357/",
            sources: {
              src: "https://cdn.pixabay.com/audio/2023/03/03/audio_f7ebce256f.mp3",
              waveformUrl: "/music/141357/waveform.json",
              thumbnailUrl:
                "https://cdn.pixabay.com/audio/2023/03/03/11-13-46-61_200x200.jpeg",
              thumbnailOrientation: "portrait",
              downloadUrl:
                "https://cdn.pixabay.com/download/audio/2023/03/03/audio_f7ebce256f.mp3?filename=news-time-141357.mp3",
            },
            alt: "",
            title: null,
            description: "",
            name: "News Time",
            nsfw: false,
            tagLinks: "",
            likeCount: 0,
            likeHref: "/accounts/like/audio/141357/",
            commentCount: 0,
            commentHref: "/music/news-time-141357/#comments",
            contentIdCertificateUrl: null,
            attributionHtml:
              'Music by <a href="https://pixabay.com/users/monument_music-34040748/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=141357">Monument_Music</a> from <a href="https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=141357">Pixabay</a>',
            vector: false,
            isEditorsChoice: false,
            isLowQuality: false,
            qualityStatus: 0,
            rating: null,
          },
        ],
      },
      {
        artist: {
          id: 13470593,
          username: "HarumachiMusic",
          firstName: "",
          lastName: "",
          avatarSrc:
            "https://cdn.pixabay.com/user/2022/05/13/10-31-22-52_96x96.png",
          profileUrl: "/users/harumachimusic-13470593/",
          socialLinks: [],
          donation: null,
          followerCount: 0,
          aboutMe: "",
        },
        media: [
          {
            id: 111327,
            mediaType: "audio",
            mediaSubType: 3,
            duration: null,
            uploadDate: "2023-03-18T06:14:09.586527",
            href: "https://pixabay.com/music/little-white-flowers-full-version-111327/",
            sources: {
              src: "https://cdn.pixabay.com/audio/2022/05/15/audio_dcc27707b3.mp3",
              waveformUrl: "/music/111327/waveform.json",
              thumbnailUrl: "",
              thumbnailOrientation: "portrait",
              downloadUrl:
                "https://cdn.pixabay.com/download/audio/2022/05/15/audio_dcc27707b3.mp3?filename=little-white-flowers-full-version-111327.mp3",
            },
            alt: "",
            title: null,
            description: "",
            name: "little white flowers (full version)",
            nsfw: false,
            tagLinks: "",
            likeCount: 0,
            likeHref: "/accounts/like/audio/111327/",
            commentCount: 0,
            commentHref:
              "/music/little-white-flowers-full-version-111327/#comments",
            contentIdCertificateUrl: null,
            attributionHtml:
              'Music by <a href="https://pixabay.com/users/harumachimusic-13470593/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=111327">Noru</a> from <a href="https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=111327">Pixabay</a>',
            vector: false,
            isEditorsChoice: false,
            isLowQuality: false,
            qualityStatus: 0,
            rating: null,
          },
        ],
      },
    ],
    themes: [
      "Music For Videos",
      "Music For Youtube Videos",
      "Vlog Music",
      "Background Music",
      "Film Music",
      "Podcast Music",
      "Cinematic Music",
    ],
  },
};
